use_default_settings: true

general:
  debug: false
  instance_name: "Websearch SearXNG"

search:
  safe_search: 1
  autocomplete: "duckduckgo"
  formats:
    - html
    - json

server:
  secret_key: "__SEARXNG_SECRET_KEY__"
  limiter: false
  image_proxy: true
  method: "GET"

valkey:
  url: false
